### ISSUE TITLE
Orientation specification required only for directionally-encoded quantities

### ISSUE THREAD

**Issue by arokem** [bids-standard/bids-bep016#79]
Currently, orientation specification details (e.g., `Directions`) are designated as `REQUIRED` metadata, but they should not be required for mdp that are directionally invariant (e.g., FA). We should clarify that. 

`SphericalHarmonicBasis` and `SphericalHarmonicDegree` are in addition also only relevant for representations that use spherical harmonics, so they should only be `REQUIRED` for those cases. Again, needs clarification.

**Comment by Lestropie** [comment]
The intention was for the prior column, "Relevant data representations", to impose restrictions at a higher level. Ie. Since `SphericalHarmonicBasis` is only "relevant" for "Spherical harmonics", the "`REQUIRED`" designation applies only when the data representation is "spherical harmonics". However you're right in that this hierarchical state of requirements of metadata is unclear.

I would add also that eg. if the data representation is *something other than* "Spherical harmonics", then a metadata field like `SphericalHarmonicBasis` *MUST NOT* be specified.

So both cases require qualification before the table is presented.
